### ISSUE TITLE
Apache v2 Licence?

### ISSUE THREAD

**Issue by mobiRic** [jack-bradshaw/SlidingIntroScreen#1]
Hello, I got to this library from the StackOverflow answer here: http://stackoverflow.com/a/35695779/383414

I would like to use it in an app due to be released next month - would it be possible to use it under Apache v2 licence, with attribution to you?

Kind regards,
Richard Le Mesurier
http://stackoverflow.com/users/383414/richard-le-mesurier

**Comment by mobiRic** [comment]
My apologies, when I started looking at the code, I found your Apache v2 licence headers.

**Comment by jack-bradshaw** [comment]
Apologies for the delay. All my code is released under an Apache v2 license, so feel free to include the library in your app :). I'd love to see the app when it's finished (if you're releasing publicly), so feel free to post a link to the play store page if you want.

**Comment by mobiRic** [comment]
I am putting the finishing touches on the Android app for South Africa's leading fast-food delivery business. Due for release in the next few weeks.

I will send you the details when we go live.

Thanks
