### ISSUE TITLE
Customize Skip, Done

### ISSUE THREAD

**Issue by ghost** [jack-bradshaw/SlidingIntroScreen#15]
Hello,
is there a way to customize the text **SKIP** and **DONE** in order to translate them to another language?

**Comment by jack-bradshaw** [comment]
From the IntroActivity you can call `getLeftButtonAccessor()` and then `setText` on the returned accessor.

**Comment by jack-bradshaw** [comment]
There are similar `getXAccessor` methods for the other buttons.

**Comment by ghost** [comment]
Perfect, thanks
