### ISSUE TITLE
how to get the click listener of Done button?

### ISSUE THREAD

**Issue by achinverma** [jack-bradshaw/SlidingIntroScreen#18]
Hi , 

i am using this lib for intro screens. Please can you tell on the last screen, 

i want to get the done button on click listener. How can i get the done button on click listener?

**Comment by achinverma** [comment]
@MatthewDavidBradshaw , @addiegupta , anyone guide me pls.

**Comment by jack-bradshaw** [comment]
```kotlin
class YourActivity : IntroActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        getFinalButtonAccessor().setOnClickListener {
            // Do something here
        }
    }
}
```
