### ISSUE TITLE
Migration from Bintray / JCenter shutdown

### ISSUE THREAD

**Issue by Daphne-CoffeeIT** [jack-bradshaw/SlidingIntroScreen#19]
[Starting from May 1, 2021 JCenter will stop working](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/). As far as I'm aware, SlidingIntroScreen is hosted on JCenter, so a migration is needed.

I know this is a relatively old library which wasn't updated in five years, but are there any plans on migrating?

Update: I ended up using another library (not for this reason in particular), so I won't respond any further. But I'll keep this issue open in case others are still wondering.

**Comment by jack-bradshaw** [comment]
I'm not sure what the best alternative is. Do you know where people are
going?

**Comment by NomadicDeveloper22** [comment]
@mattbradshaw001 jitpack.io and maven central seem to be the standards now

**Comment by DonaldDuck313** [comment]
@jack-bradshaw Any updates on this? I have a project that won't compile anymore because it can't find this library. By default, Android Studio adds the following to build.gradle:

```
repositories {
    google()
    mavenCentral()
}
```

So it would be good if you could publish this library on one of those repositories.

**Comment by jack-bradshaw** [comment]
Hello. This repo isn’t maintained anymore and there isn’t a fix coming.
