### ISSUE TITLE
Allow custom theme in IntroActivity

### ISSUE THREAD

**Issue by mobiRic** [jack-bradshaw/SlidingIntroScreen#2]
Hello, further to previous issue.

Unfortunately the current library does not allow for custom theming of the main activity. A workaround is to set the background of my custom IntroActivity after calling into your `super.onCreate()` method, but this means there is a slight flash before my background becomes visible.

Allowing a way to override the default theme you provide would get around this limitation. 

This is a change I will seek to make on my side and will issue a pull-request once your repo is back up and running, if it is something that would be useful on your side.

Regards,
Richard

**Comment by jack-bradshaw** [comment]
I hope to have the new code up very shortly. I'm just writing my last tests now. I wasn't aware of this issue, so I've quickly fixed it in my code; you should be able to set a custom theme in the new version.

**Comment by mobiRic** [comment]
I have sorted that out as well, and made a few other minor changes for our purposes.

Once you put your code up, I'll pull the repo again and then see if you want to take any of our updates up into your code.

**Comment by jack-bradshaw** [comment]
Fixed in version 2.0.0.
