### ISSUE TITLE
TOUCH_LOCKED as LockMode Locks everything

### ISSUE THREAD

**Issue by seang96** [jack-bradshaw/SlidingIntroScreen#5]
Everything gets locked when TOUCH_LOCKED is enabled, not just the navigation which makes it difficult to require the user to interact with something to go to the next page.

**Comment by jack-bradshaw** [comment]
Thanks, I'll look into it. I've probably overridden onTouchEventIntercepted() incorrectly.

**Comment by jack-bradshaw** [comment]
Fixed in version 3.1.0
