### ISSUE TITLE
'Compile' vs. 'Provided' for AppCompat

### ISSUE THREAD

**Issue by milosmns** [jack-bradshaw/SlidingIntroScreen#8]
I noticed you used `compile` instead of `provided` for including the AppCompat dependency, here: https://github.com/MatthewTamlin/SlidingIntroScreen/blob/master/library/build.gradle#L21

Any chance you can switch to `provided`? I'd really hate to include it twice in my app with possibly different versions, and I don't use ProGuard to slim down the app (still not hitting the 65k limit).

Thanks!

**Comment by jack-bradshaw** [comment]
While I can appreciate your situation and what you're trying to achieve, I don't believe that changing the dependency to `provided` (or `compileOnly` as it's known in Gradle) is the best course of action. It can be useful or even necessary in some situations, but I don't believe this is one of them. They're useful if:
- A dependent feature is optional.
- The dependency is not required or not available at runtime.
- The implementation is determined at runtime by another library.

My library definitely doesn't have any optional features and the dependency is definitely required at runtime, so the first two points are definitely not applicable. The third point initially seems like it might be applicable, but upon further consideration it isn't. Allowing the implementation to be determined at runtime by whichever app compat library is being used would reduce the effectiveness of my tests and it would potentially create very difficult to find bugs. If a consumer supplied a version of the dependency containing a defect, it could cause my library to behave defectively too. I'm definitely not in a position to test every possible app compat library so it's preferable for me to stick with one dependency at compile time.

You said you don't use proguard, but I think that's the tool you should be using. It can be used for much more than just avoiding the 65K limit.
