### ISSUE TITLE
Always returns null

### ISSUE THREAD

**Issue by neutt22** [jack-bradshaw/SlidingIntroScreen#9]
https://github.com/MatthewTamlin/SlidingIntroScreen/blob/34c9c05ab35bf9c4f0a7883f3a5934e083797df0/example%20app/src/main/java/com/matthewtamlin/sliding_intro_screen_example_app/NumberFragment.java#L25 never set the number because the `onCreateView` was called AFTER `setNumber`

**Comment by jack-bradshaw** [comment]
Bugs in the sample app aren't a priority and won't be fixed.
